/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.mysql.jdbc.Connection;
import com.sun.istack.internal.Pool;
import java.util.ArrayList;
import java.util.Date;
import java.util.Observable;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import logical.Servicio;
import model.Multa;
import model.Respuesta;

/**
 *
 * @author Muneca
 */
public class Borrados extends javax.swing.JFrame {
    
    final MessageObservable observable = new MessageObservable ();
    
    ArrayList <Multa> ArrayListBorradas = new ArrayList();
    
    public Borrados(ArrayList<Multa> lstBorradas, Registro registro) {
        initComponents();
        System.err.print("cantidad: "+lstBorradas.size());
        llenarTabla (lstBorradas);
        observable.addObserver(registro);
        ArrayListBorradas = lstBorradas;
    }
    
    class MessageObservable extends Observable{
        MessageObservable (){
            super ();
        }
        void changeData (Object data){
            setChanged ();
            notifyObservers (data);
        }
    }
        
        private void llenarTabla (ArrayList<Multa> lista){
        DefaultTableModel model = new DefaultTableModel (new String []{"#", "DNI", "Multa", "Monto", "Correo", "Punto","Id"},0);
            int i = 1;
            for (Multa m : lista){
                model.addRow(new Object []{i, m.getDni(), m.getMulta(), m.getMonto(), m.getCorreo(), m.getPunto(), m.getIdMulta()});
                i++;
            }

            lstBorrados = new JTable (model);
            lstBorrados.removeColumn(lstBorrados.getColumnModel().getColumn(6));
            ListSelectionListener lel = new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent event) {
                if(!event.getValueIsAdjusting()) {
                    setearDatos();
                }
            }
        };
            lstBorrados.getSelectionModel().addListSelectionListener(lel);
            jScrollPane1.setViewportView(lstBorrados);
        }
    
        
       
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstBorrados = new javax.swing.JTable();
        btnRestaurar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lstBorrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "DNI", "Multa", "Monto", "Correo", "Puntos"
            }
        ));
        lstBorrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lstBorradosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(lstBorrados);

        btnRestaurar.setText("Restaurar");
        btnRestaurar.setEnabled(false);
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(btnRestaurar)
                        .addGap(34, 34, 34)
                        .addComponent(btnEliminar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnRestaurar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstBorradosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstBorradosMousePressed

        // TODO add your handling code here:
    }//GEN-LAST:event_lstBorradosMousePressed
    
    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed
    if (multarestaurar.getDni()== null){
        return;
    }
    
    observable.changeData(multarestaurar);
    String idMulta = lstBorrados.getModel().getValueAt(lstBorrados.getSelectedRow(), 6  )+"";
    for (Multa m: ArrayListBorradas){
        if(m.getIdMulta() == Integer.parseInt (idMulta)){
          Servicio servicio = new Servicio ();
          Respuesta rpta = new Respuesta();
          rpta = servicio.borrarMulta (Integer.parseInt (idMulta));
          ArrayListBorradas.remove(m);
          llenarTabla (ArrayListBorradas);   
        }
    } 
        
    }//GEN-LAST:event_btnRestaurarActionPerformed
    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    if (multarestaurar.getDni()== null){
        return;
    }
        
    String idMulta = lstBorrados.getModel().getValueAt(lstBorrados.getSelectedRow(), 6  )+"";
    for (Multa m: ArrayListBorradas){
        if(m.getIdMulta() == Integer.parseInt (idMulta)){
          Servicio servicio = new Servicio ();
          Respuesta rpta = new Respuesta();
          rpta = servicio.borrarMulta (Integer.parseInt (idMulta));
          ArrayListBorradas.remove(m);
          llenarTabla (ArrayListBorradas);   
        }
    }
    
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    Multa multarestaurar = new Multa ();
        
    private void setearDatos() {
        String dni    = lstBorrados.getModel().getValueAt(lstBorrados.getSelectedRow(), 1  )+"";
        String multa  = lstBorrados.getModel().getValueAt(lstBorrados.getSelectedRow(), 2  )+"";
        String monto  = lstBorrados.getModel().getValueAt(lstBorrados.getSelectedRow(), 3 )+"";
        String correo = lstBorrados.getModel().getValueAt(lstBorrados.getSelectedRow(), 4  )+"";
        String punto  = lstBorrados.getModel().getValueAt(lstBorrados.getSelectedRow(), 5  )+"";
        System.err.println(dni+" - "+multa+" - "+monto+" - "+correo+" - "+punto);
        
        
        multarestaurar.setDni(dni);
        multarestaurar.setMulta(multa);
        multarestaurar.setMonto(Double.parseDouble(monto));
        multarestaurar.setCorreo(correo);
        multarestaurar.setPunto(Integer.parseInt(punto));
        multarestaurar.setFecha(new Date());
        
        btnRestaurar.setEnabled(true);
        btnEliminar.setEnabled(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Borrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Borrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Borrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Borrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Borrados(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lstBorrados;
    // End of variables declaration//GEN-END:variables
}
