/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.JFrame;
import logical.Conexion;
import model.Multa;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import static view.Registro.n;

/**
 *
 * @author Muneca
 */
public class Principal extends javax.swing.JFrame {
    ArrayList<Multa> lstMultasBorradas = new ArrayList<>();
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        RegistroMulta = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ReporteTipoMulta = new javax.swing.JMenuItem();
        ReporteExistentesBD = new javax.swing.JMenuItem();
        ReporteMultaDNI = new javax.swing.JMenuItem();
        DetalleReporte = new javax.swing.JMenu();
        ReporteAltaVelocidad = new javax.swing.JMenuItem();
        ReportePicoPlaca = new javax.swing.JMenuItem();
        ReporteLuzRoja = new javax.swing.JMenuItem();
        ReporteMalEstacionado = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 786, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        jMenu1.setText("Sistema");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        RegistroMulta.setText("Registro Multas");
        RegistroMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroMultaActionPerformed(evt);
            }
        });
        jMenu1.add(RegistroMulta);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reportes");

        ReporteTipoMulta.setText("Por Tipo de Multa");
        ReporteTipoMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteTipoMultaActionPerformed(evt);
            }
        });
        jMenu2.add(ReporteTipoMulta);

        ReporteExistentesBD.setText("Existentes en BD");
        ReporteExistentesBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteExistentesBDActionPerformed(evt);
            }
        });
        jMenu2.add(ReporteExistentesBD);

        ReporteMultaDNI.setText("Multa por DNI");
        ReporteMultaDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteMultaDNIActionPerformed(evt);
            }
        });
        jMenu2.add(ReporteMultaDNI);

        DetalleReporte.setText("Detalle de Reportes");

        ReporteAltaVelocidad.setText("Alta Velocidad");
        ReporteAltaVelocidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteAltaVelocidadActionPerformed(evt);
            }
        });
        DetalleReporte.add(ReporteAltaVelocidad);

        ReportePicoPlaca.setText("Pico Placa");
        ReportePicoPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportePicoPlacaActionPerformed(evt);
            }
        });
        DetalleReporte.add(ReportePicoPlaca);

        ReporteLuzRoja.setText("Luz Roja");
        ReporteLuzRoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteLuzRojaActionPerformed(evt);
            }
        });
        DetalleReporte.add(ReporteLuzRoja);

        ReporteMalEstacionado.setText("Mal Estacionado");
        ReporteMalEstacionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteMalEstacionadoActionPerformed(evt);
            }
        });
        DetalleReporte.add(ReporteMalEstacionado);

        jMenu2.add(DetalleReporte);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistroMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroMultaActionPerformed
    Registro abrir = new Registro();
    abrir.setVisible(true); 
    
    
// TODO add your handling code here:
    }//GEN-LAST:event_RegistroMultaActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
    
// TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void ReporteTipoMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteTipoMultaActionPerformed
     
    try {
        JasperReport jr = (JasperReport) JRLoader.loadObject(Registro.class.getResource("../Reportes/ReporteMultas.jasper"));
        JasperPrint jp = JasperFillManager.fillReport(jr, null, Conexion.startConeccion());
        JasperViewer jv = new JasperViewer(jp,false);
        jv.show();
        } catch (Exception e) {
              // TODO add your handling code here:
    }           


        // TODO add your handling code here:
    }//GEN-LAST:event_ReporteTipoMultaActionPerformed

    private void ReporteExistentesBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteExistentesBDActionPerformed
      
    try {
        JasperReport jr = (JasperReport) JRLoader.loadObject(Registro.class.getResource("../Reportes/ReporteExistentes.jasper"));
        JasperPrint jp = JasperFillManager.fillReport(jr, null, Conexion.startConeccion());
        JasperViewer jv = new JasperViewer(jp,false);
        jv.show();
        } catch (Exception e) {
                // TODO add your handling code here:
    }        

        // TODO add your handling code here:
    }//GEN-LAST:event_ReporteExistentesBDActionPerformed

    private void ReporteMultaDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteMultaDNIActionPerformed
         
    try {
        JasperReport jr = (JasperReport) JRLoader.loadObject(Registro.class.getResource("../Reportes/ReportePorDNI.jasper"));
        JasperPrint jp = JasperFillManager.fillReport(jr, null, Conexion.startConeccion());
        JasperViewer jv = new JasperViewer(jp,false);
        jv.show();
        } catch (Exception e) {
                // TODO add your handling code here:
    } 
    
// TODO add your handling code here:
    }//GEN-LAST:event_ReporteMultaDNIActionPerformed

    private void ReporteAltaVelocidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteAltaVelocidadActionPerformed
    try {
        JasperReport jr = (JasperReport) JRLoader.loadObject(Registro.class.getResource("../Reportes/ReporteDetalleAltaVelocidad.jasper"));
        JasperPrint jp = JasperFillManager.fillReport(jr, null, Conexion.startConeccion());
        JasperViewer jv = new JasperViewer(jp,false);
        jv.show();
        } catch (Exception e) {
              // TODO add your handling code here:
    }    


        // TODO add your handling code here:
    }//GEN-LAST:event_ReporteAltaVelocidadActionPerformed

    private void ReportePicoPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportePicoPlacaActionPerformed
    try {
        JasperReport jr = (JasperReport) JRLoader.loadObject(Registro.class.getResource("../Reportes/ReporteDetallePicoPlaca.jasper"));
        JasperPrint jp = JasperFillManager.fillReport(jr, null, Conexion.startConeccion());
        JasperViewer jv = new JasperViewer(jp,false);
        jv.show();
        } catch (Exception e) {
              // TODO add your handling code here:
    }    
        
// TODO add your handling code here:
    }//GEN-LAST:event_ReportePicoPlacaActionPerformed

    private void ReporteLuzRojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteLuzRojaActionPerformed

    try {
        JasperReport jr = (JasperReport) JRLoader.loadObject(Registro.class.getResource("../Reportes/ReporteDetalleLuzRoja.jasper"));
        JasperPrint jp = JasperFillManager.fillReport(jr, null, Conexion.startConeccion());
        JasperViewer jv = new JasperViewer(jp,false);
        jv.show();
        } catch (Exception e) {
              // TODO add your handling code here:
    }        

        // TODO add your handling code here:
    }//GEN-LAST:event_ReporteLuzRojaActionPerformed

    private void ReporteMalEstacionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteMalEstacionadoActionPerformed
    try {
        JasperReport jr = (JasperReport) JRLoader.loadObject(Registro.class.getResource("../Reportes/ReporteDetalleMalEstacionado.jasper"));
        JasperPrint jp = JasperFillManager.fillReport(jr, null, Conexion.startConeccion());
        JasperViewer jv = new JasperViewer(jp,false);
        jv.show();
        } catch (Exception e) {
              // TODO add your handling code here:
    }        


        // TODO add your handling code here:
    }//GEN-LAST:event_ReporteMalEstacionadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu DetalleReporte;
    private javax.swing.JMenuItem RegistroMulta;
    private javax.swing.JMenuItem ReporteAltaVelocidad;
    private javax.swing.JMenuItem ReporteExistentesBD;
    private javax.swing.JMenuItem ReporteLuzRoja;
    private javax.swing.JMenuItem ReporteMalEstacionado;
    private javax.swing.JMenuItem ReporteMultaDNI;
    private javax.swing.JMenuItem ReportePicoPlaca;
    private javax.swing.JMenuItem ReporteTipoMulta;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
