/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Observable;
import java.util.Observer;
import java.util.function.Predicate;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.runtime.regexp.joni.Regex;
import logical.Conexion;
import logical.ReglasNegocio;
import logical.Servicio;
import model.Multa;
import model.Respuesta;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Muneca
 */
public class Registro extends javax.swing.JFrame implements Observer {
    
    ArrayList<Multa> lstMultas = new ArrayList<>();
    ArrayList<Multa> lstMultasBorradas = new ArrayList<>();
    ArrayList<String> lstTipoMultas = new ArrayList<>();
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        initComponents2();
        Servicio servicio = new Servicio ();
        lstMultas = servicio.getMultas();
        lstTipoMultas = servicio.getTiposMulta();
        if (lstMultas == null){
            System.err.print("La lista es null");
        }else {
            System.err.print("LISTA: "+lstMultas.size());
        }

        llenarTabla(lstMultas);
        llenarComboTipoMulta (lstTipoMultas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cboTipos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMultas = new javax.swing.JTable();
        btnRegistrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPunto = new javax.swing.JTextField();
        btnRefrescar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblDniError = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JFormattedTextField();
        txtBuscar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnBorrados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("DNI");

        txtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIActionPerformed(evt);
            }
        });
        txtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDNIKeyTyped(evt);
            }
        });

        jLabel2.setText("Tipo");

        cboTipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  :::Selec. Multa:::" }));
        cboTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTiposActionPerformed(evt);
            }
        });

        jLabel3.setText("Monto");

        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });
        txtMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoKeyTyped(evt);
            }
        });

        jLabel4.setText("Correo");

        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoFocusLost(evt);
            }
        });
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        tblMultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "#", "DNI", "Multa", "Monto", "Correo", "Puntos"
            }
        ));
        tblMultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblMultasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblMultas);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jLabel5.setText("Punto");

        txtPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPuntoActionPerformed(evt);
            }
        });
        txtPunto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPuntoKeyTyped(evt);
            }
        });

        btnRefrescar.setText("Refrescar");
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        lblDniError.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        lblDniError.setForeground(new java.awt.Color(255, 51, 0));

        jLabel7.setText("Fecha");

        txtFecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFechaFocusLost(evt);
            }
        });

        jLabel8.setText("Busqueda Directa");

        btnBorrados.setText("Borrados");
        btnBorrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorradosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(25, 25, 25)
                                .addComponent(txtPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(23, 23, 23)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBorrar)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboTipos, 0, 124, Short.MAX_VALUE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDniError, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnRegistrar)
                                .addGap(56, 56, 56)
                                .addComponent(btnBorrados)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRefrescar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(txtCorreo))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(cboTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDniError, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtPunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnBorrar)
                    .addComponent(btnRefrescar)
                    .addComponent(btnBorrados))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void llenarComboTipoMulta(ArrayList<String> lstTipoMultas) {
        DefaultComboBoxModel dml = new DefaultComboBoxModel();
        dml.addElement("::: Selec. Multa :::");
        for (String descTipMulta : lstTipoMultas) {
            dml.addElement(descTipMulta);
        }
        cboTipos.setModel(dml);
    }
    
    
    private void initComponents2() {
        
        
        
        txtDNI.getDocument().addDocumentListener(new DocumentListener() {
            
            public void insertUpdate(DocumentEvent e) {
                 warn();//To change body of generated methods, choose Tools | Templates.
            }

           
            public void removeUpdate(DocumentEvent e) {
                warn();////To change body of generated methods, choose Tools | Templates.
            }

            
            public void changedUpdate(DocumentEvent e) {
                warn();// //To change body of generated methods, choose Tools | Templates.
            }

            public void warn() {
                String dni = txtDNI.getText();
                validarDNI (dni);
            }

            
        });
     txtBuscar.getDocument().addDocumentListener(new DocumentListener() {
            
            public void insertUpdate(DocumentEvent e) {
                 warn();//To change body of generated methods, choose Tools | Templates.
            }

           
            public void removeUpdate(DocumentEvent e) {
                warn();////To change body of generated methods, choose Tools | Templates.
            }

            
            public void changedUpdate(DocumentEvent e) {
                warn();// //To change body of generated methods, choose Tools | Templates.
            }

            public void warn() {
                String busqueda = txtBuscar.getText();
                if(busqueda.length() == 0) {
                    llenarTabla (lstMultas);
                    return;
                }
            Predicate<Multa> byDni = multa -> multa.getDni().contains(busqueda);
            Predicate<Multa> byMulta = multa -> multa.getMulta().toLowerCase().contains(busqueda.toLowerCase());
            ArrayList<Multa> listaFiltradaDNI   = (ArrayList) lstMultas.stream().filter(byDni).collect(Collectors.toList());
            ArrayList<Multa> listaFiltradaMulta = (ArrayList) lstMultas.stream().filter(byMulta).collect(Collectors.toList());
            listaFiltradaDNI.addAll(listaFiltradaMulta);
            llenarTabla(listaFiltradaDNI);
            }
  
        });   
    }
      
       
    int idMultaModif = 0;
    
    private void setearDatos() {
        String dni    = tblMultas.getModel().getValueAt(tblMultas.getSelectedRow(), 1  )+"";
        String multa  = tblMultas.getModel().getValueAt(tblMultas.getSelectedRow(), 2  )+"";
        String monto  = tblMultas.getModel().getValueAt(tblMultas.getSelectedRow(), 3 )+"";
        String correo = tblMultas.getModel().getValueAt(tblMultas.getSelectedRow(), 4  )+"";
        String punto  = tblMultas.getModel().getValueAt(tblMultas.getSelectedRow(), 5  )+"";
        String idMulta = tblMultas.getModel().getValueAt(tblMultas.getSelectedRow(), 6  )+"";
        System.err.println(dni+" - "+multa+" - "+monto+" - "+correo+" - "+punto+" - "+idMulta);
        idMultaModif = Integer.parseInt(idMulta);
        txtDNI.setText(dni);
        txtDNI.setEnabled(false);
        cboTipos.setSelectedItem(multa);
        txtMonto.setText(monto);
        txtCorreo.setText(correo);
        txtPunto.setText(punto);
        btnRegistrar.setText("Actualizar");
        btnBorrar.setEnabled(true);
    }
    private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIActionPerformed

    private void cboTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTiposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTiposActionPerformed

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        
// TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed
    ReglasNegocio validarDatos = new ReglasNegocio ();
    
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String sDNI;
        String sMonto;
        String sPunto;
        String sMulta;
        String sCorreo;
        String sFecha;
        
        sDNI = txtDNI.getText();
        sMonto = txtMonto.getText();
        sPunto = txtPunto.getText();
        sMulta = cboTipos.getSelectedItem().toString();
        sCorreo = txtCorreo.getText();
        sFecha = txtFecha.getText();
        
        validarDatos.validarDatos(sDNI, sMonto, sPunto, sMulta, sCorreo, sFecha);

        // TODO add your handling code here:
        try {
            String dni = txtDNI.getText();
            if(!dni.matches("[0-9]+")) {
                lblDniError.setText("El número de DNI es incorrecto.");
                return;
            }
            if(dni.length() != 8) {
                lblDniError.setText("El número de DNI tiene que ser 8 caracteres.");
                return;
            }
            String multa  = cboTipos.getSelectedItem().toString();
            String montoTexto = txtMonto.getText();
            // validar
            
            String correo = txtCorreo.getText();
            int punto     = Integer.parseInt(txtPunto.getText());
            String fecha  = txtFecha.getText();
           
           
            Date fechaMulta = (Date) new SimpleDateFormat("dd/MM/yyyy").parse(fecha); 
           
            //validarCampos();
            
            Double monto  = Double.parseDouble(montoTexto);
            
            Multa objMulta = new Multa();
            objMulta.setDni(dni);
            objMulta.setMulta(multa);
            objMulta.setMonto(monto);
            objMulta.setCorreo(correo);
            objMulta.setPunto(punto);
            objMulta.setFecha(fechaMulta);
            
            

            Servicio servicio = new Servicio();
            Respuesta rpta = new Respuesta();
            if(idMultaModif == 0) {
                rpta = servicio.insertarMultaProcedure(objMulta);
            } else {
                objMulta.setIdMulta(idMultaModif);
                rpta = servicio.actualizarMulta(objMulta);
            }
            System.err.println(rpta.toString());
            if(rpta.getCodigo() == 0) {
                if(idMultaModif == 0) {
                    lstMultas.add(objMulta);
                } else {
                    for(Multa m : lstMultas) {
                        if(m.getIdMulta() == objMulta.getIdMulta()) {
                            m.setCorreo(correo);
                            m.setMonto(monto);
                            m.setMulta(multa);
                            m.setPunto(punto);
                            break;
                        }
                    }
                }
                limpiarForm();
                llenarTabla(lstMultas);
            }
            JOptionPane.showMessageDialog(this, rpta.getMsj());
        } catch (Exception e) {
            e.printStackTrace();
        }
    
    }//GEN-LAST:event_btnRegistrarActionPerformed
    private void limpiarForm(){
        txtDNI.setText(null);
        cboTipos.setSelectedIndex(0);
        txtMonto.setText(null);
        txtCorreo.setText(null);
        txtPunto.setText(null);
        btnRegistrar.setText("Registrar");
        btnBorrar.setEnabled(false);
        txtDNI.setEnabled(true);
    }

    private void txtPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPuntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPuntoActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed

    Servicio servicio = new Servicio ();
    lstMultas = servicio.getMultas();
    llenarTabla(lstMultas);   
// TODO add your handling code here:
    }//GEN-LAST:event_btnRefrescarActionPerformed


    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
    int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog (null, "¿Estas seguro de borrar la muta?", "Warning", dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
            Servicio servicio = new Servicio();
            Respuesta rpta = new Respuesta();
            rpta = servicio.borrarMulta(idMultaModif);
            System.err.println(rpta.toString());
            if(rpta.getCodigo() == 0) {
                for(Multa m : lstMultas) {
                    if(m.getIdMulta() == idMultaModif) {
                        lstMultas.remove(m);
                        lstMultasBorradas.add(m);
                        break;
                    }
                }
                limpiarForm();
                llenarTabla(lstMultas);
                btnBorrados.setEnabled(true);
            }
            JOptionPane.showMessageDialog(this, rpta.getMsj());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void tblMultasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMultasMousePressed
       
            // TODO add your handling code here:
    }//GEN-LAST:event_tblMultasMousePressed

    private void btnBorradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorradosActionPerformed
        if (lstMultasBorradas.size ()== 0){
            return;
        }
        
        Borrados frame = new Borrados(lstMultasBorradas, n);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorradosActionPerformed

    private void txtDNIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIKeyTyped
    
        char validar =evt.getKeyChar();
        if (Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo números");
        }
        if (txtDNI.getText().length() >= 8){
            evt.consume();
        }
        
    }//GEN-LAST:event_txtDNIKeyTyped

    private void txtMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoKeyTyped
        char validar =evt.getKeyChar();
        if (Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo números");
        }
    }//GEN-LAST:event_txtMontoKeyTyped

    private void txtPuntoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPuntoKeyTyped
        char validar =evt.getKeyChar();
        if (Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo números");
        }
    }//GEN-LAST:event_txtPuntoKeyTyped
    
    public boolean isEmail (String correo){
        Pattern pat = null;
        Matcher mat = null;
        pat = Pattern.compile("^[\\w\\-\\_\\+]+(\\.[\\w\\-\\_]+)*@([A-Za-z0-9-]+\\.)+[A-Za-z]{2,4}$");
        mat = pat.matcher(correo);
        if(mat.find()){
            return true;
        }else{
            return false;
        }
        
    }
    
    private void txtCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusLost
        if(!isEmail(txtCorreo.getText())){
            JOptionPane.showMessageDialog(null, "¡Debes validar el email!", "ATENCIÓN ADMINISTRADOR", JOptionPane.WARNING_MESSAGE);
            txtCorreo.requestFocus();
        }
        
        
    }//GEN-LAST:event_txtCorreoFocusLost
    
    private void txtFechaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFechaFocusLost
        Date sistFecha  = new  Date ();
        
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        txtFecha.setText(formato.format(sistFecha));
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaFocusLost
    private void buscador(String busqueda) {
        Predicate<Multa> byDni = multa -> multa.getDni().contains(busqueda);
        Predicate<Multa> byMulta = multa -> multa.getMulta().toLowerCase().contains(busqueda.toLowerCase());
        ArrayList<Multa> listaFiltradaDNI   = (ArrayList) lstMultas.stream().filter(byDni).collect(Collectors.toList());
        ArrayList<Multa> listaFiltradaMulta = (ArrayList) lstMultas.stream().filter(byMulta).collect(Collectors.toList());
        listaFiltradaDNI.addAll(listaFiltradaMulta);
        llenarTabla(listaFiltradaDNI);
    }
    private void validarDNI (String dni){
        btnRegistrar.setEnabled(false);
            if(dni.length() == 0) {
                lblDniError.setText(null);
                return;
            }
            //if(!dni.matches("[0-9]+")) {
              // lblDniError.setText("El número de DNI es incorrecto.");
               // return;
            // } else {
               // lblDniError.setText(null);
            // }
            if(dni.length() != 8) {
                lblDniError.setText("El número de DNI tiene que ser 8 caracteres.");
                return;
            } else {
                lblDniError.setText(null);
            }
            btnRegistrar.setEnabled(true);
    }
    
    private void llenarTabla (ArrayList<Multa> lista){
        DefaultTableModel model = new DefaultTableModel (new String []{"#", "DNI", "Multa", "Monto", "Correo", "Punto","Id"},0);
            int i = 1;
            for (Multa m : lista){
                model.addRow(new Object []{i, m.getDni(), m.getMulta(), m.getMonto(), m.getCorreo(), m.getPunto(), m.getIdMulta()});
                i++;
            }

            tblMultas = new JTable (model);
            tblMultas.removeColumn(tblMultas.getColumnModel().getColumn(6));
            ListSelectionListener lel = new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent event) {
                if(!event.getValueIsAdjusting()) {
                    setearDatos();
                }
            }
        };
            tblMultas.getSelectionModel().addListSelectionListener(lel);
            jScrollPane1.setViewportView(tblMultas);
    }
     @Override
    public void update(Observable o, Object arg) {
        Multa mulRest = (Multa) arg;
        System.err.print(mulRest.getCorreo());
        
        Servicio servicio = new Servicio();
        Respuesta rpta = new Respuesta();
        rpta = servicio.insertarMulta(mulRest);
        mulRest.setIdMulta (rpta.getIdGenerado());
        
        if(rpta.getCodigo() == 0) {
                lstMultas.add(mulRest);
                limpiarForm();
                llenarTabla(lstMultas);
            }
            JOptionPane.showMessageDialog(this, rpta.getMsj());
    }
    
    /**
     * @param args the command line arguments
     */
    static Registro n = new Registro ();
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                n.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrados;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cboTipos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDniError;
    private javax.swing.JTable tblMultas;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtPunto;
    // End of variables declaration//GEN-END:variables

   
    
}
